version: '3.8'

services:
  localhost:
    image: 'postgres:10'
    container_name: 'java-postSQL'
    ports:
      - "80:8080"
    environment:
      SERVER_PORT: 8080
      POSTGRES_USER: postgres
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: jdbc:postgresql://localhost:5432/Restaurant
      POSTGRES_PASSWORD: Xemyru

  database:
    image: postgres:latest
    restart: always
    container_name: 'localhost'
    ports:
      - "5432:5432"

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Xemyru

  app:
    build: /.
    container_name: 'java-application'
    ports:
      - '9000:8080'